### ISSUE TITLE
Consider writing thesis in programmatic format

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/project_management#1]
# Tools

## [Quarto](https://quarto.org/)
An open-source scientific and technical publishing system
Basically Rmarkdown on steroids.

## [`Bookdown`](https://github.com/rstudio/bookdown)
A open-source (GPL-3) R package to facilitate writing books and long-form articles/reports with R Markdown.  

## [`Biocbook`](https://github.com/js2264/BiocBook)  
BiocBooks are package-based, versioned online books with a supporting Docker image for each book version.

## [`trackdown`](https://cran.r-project.org/web/packages/trackdown/vignettes/trackdown-workflow.html)
Write in rmarkdown/quarto, upload to Google Docs for collaborators to edit, download again.

## [`targets`](https://books.ropensci.org/targets/)
Pipeline tools coordinate the pieces of computationally demanding analysis projects. 

# Tutorials
- [x] https://quarto.org/docs/get-started/hello/rstudio.html
- [x] https://biostats-r.github.io/biostats/quarto/
- [x] https://cameronpatrick.com/post/2023/07/quarto-thesis-formatting/
- [x] https://bookdown.org/thea_knowles/dissertating_rmd_presentation/
- [x] https://www.njtierney.com/post/2022/04/11/rmd-to-qmd/
- [x] https://bookdown.org/pdr_higgins/rmrwr/quarto-is-a-next-generation-rmarkdown.html

# Templates
- [x] https://github.com/biostats-r/quartothesis
- [x] https://github.com/nmfs-opensci/quarto-thesis
- [x] https://quarto.org/docs/journals/templates.html
- [x] [`thesisdown`](https://github.com/ismayc/thesisdown)
- [x] [`oxforddown`](https://ulyngs.github.io/oxforddown/)
- [x] [LaTeX template for Imperial College London PhD Thesis](https://github.com/bardsoftware/template-thes-icl)
- [x] [imperial-college-london-phd-thesis-latex-template](https://www.overleaf.com/latex/templates/imperial-college-london-phd-thesis-latex-template/zfybynnyczhb)
 
# Test

Code:
https://github.com/bschilder/thesis
HTML:
https://bschilder.github.io/thesis/
PDF:

**Comment by NathanSkene** [comment]
Would be cool if you can figure out a way. Guess you’d need a way to make it so compiling each bit is done independently, e.g. you’re not recomputing everything everytime.

**Comment by bschilder** [comment]
For the rare disease manuscript, using the Quarto manuscript format:
https://github.com/neurogenomics/rare_disease_celltyping/tree/master/manuscript

For my thesis, using multiple Quarto docs (by chapter) bundled into one BiocBook:
https://github.com/bschilder/thesis/
